### ISSUE TITLE
readme images

### ISSUE THREAD

**Issue by nolan-cerebras** [ndey96/SaveMe-iPhone#1]
![group](https://cloud.githubusercontent.com/assets/10405248/12497415/a6c725b0-c069-11e5-91bf-b26fc279aaae.png)
![group1](https://cloud.githubusercontent.com/assets/10405248/12497417/a6d96950-c069-11e5-9f1d-0bdd25eb1fa6.png)
![group3](https://cloud.githubusercontent.com/assets/10405248/12497416/a6d4b1d0-c069-11e5-87b3-e8c7df2f8995.png)

**Comment by LaurierMantel** [comment]
Maybe reopen? Images could use a refresh w/ iOS 12.
